# name: update Vercel ENV and deploy for project bgt-market

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '.github/workflows/.env.bgt-market'
#       - '.github/workflows/bgt-market.deployment.yml'
#       - '.github/scripts/update-env.js'
#       - 'apps/bgt-market/**'

# jobs:
#   deploy_bgt-market:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 9.1.2 # 指定与 `pnpm-lock.yaml` 兼容的版本

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           cache: 'pnpm'

#       - name: Export secrets to env
#         uses: oNaiPs/secrets-to-env-action@v1
#         with:
#           secrets: ${{ toJSON(secrets) }}

#       - name: Process env file with Node.js
#         env:
#           ENV_FILE: .github/workflows/.env.bgt-market
#           PROJECT_NAME: bgt-market
#           PROJECT_ID: prj_Yhv6hufFe068byTjwTCRds5PP4YB
#         run: |
#           pnpm add axios dotenv fs --global
#           export NODE_PATH=$(pnpm root -g)
#           node .github/scripts/update-env.js

#       - name: Install Vercel CLI
#         run: npm install -g vercel@22.0.1

#       - name: Deploy to Vercel Action
#         uses: BetaHuhn/deploy-to-vercel-action@develop
#         env:
#           PROJECT_ID: prj_Yhv6hufFe068byTjwTCRds5PP4YB
#         with:
#           GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
#           VERCEL_TOKEN: ${{ secrets.WORKFLOW_VERCEL_TOKEN }}
#           VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
#           VERCEL_PROJECT_ID: ${{ env.PROJECT_ID }}
